include: package:very_good_analysis/analysis_options.yaml

analyzer:  
  exclude: 
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.pb.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbserver.dart"
    - "**/core/services/database/**"

linter: 
  rules: 
    public_member_api_docs: false
